services:
  crus:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      no_cache: true
      network: host
    ports:
      - "9090:9090"
    network_mode: host
    logging:
      driver: "local"
    volumes:
      - db:/mam/hyoo/crus/app/run/-/.crus
      - local:/root/.local/share/mol_state_local
    restart: always

volumes:
  db:
  local:
